env: 
  - DATABASE_NAME=superlists DATABASE_USER: postgres

language: python
python:
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install -r requirements.txt"
#before teste
before_script:
    - psql -c 'create database superlists;' -U postgres
    - python manage.py runserver 0.0.0.0:8000 &
# command to run tests
script: python manage.py test functional_tests
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
