env: 
  - DATABASE_NAME=superlists DTABASE_USER: postgres

language: python
python:
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install -r requirements.txt"
#before teste
before_script:
    - psql -c 'create database superlists;' -U postgres
# command to run tests
script: python manage.py test functional_tests
