---

- name: Provision a {{ application_name }} db server
  hosts: dbservers
  sudo: yes
  sudo_user: root
  remote_user: "{{remoteu}}"
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    - env_vars/pass.yml # always use last

  roles:
    - pip
    - base
    - db
