---

- hosts: all
  user: root

  vars_files:
    - env_vars/sshkey.yml
    - env_vars/pass.yml # always use last

  
  tasks:
  
#  - name: update apt-cache
#    apt: update_cache=yes name=sudo # name is fake

  - name: install language packs {{language_packs}} 
    command: apt-get install {{language_packs}} -y
    tags: locale
  
  - name: copy /etc/default/locale file from management machine to host
    copy: src=/etc/default/locale dest=/etc/default/locale owner=root group=root mode=0644
    tags: locale


  - name: Create group "{{remote_group}}"
    group: name="{{remote_group}}" state=present
    tags: user

  - name: Setup | create user "{{remote_user}}"
    user:  name="{{remote_user}}" shell=/bin/bash state=present groups="sudo,{{ remote_group }}" password="{{ remote_password }}" comment="Deploy user"
    tags: user
 
    
  - name: Setup | authorized key upload
    authorized_key: user="{{remote_user}}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 
    tags: key

  - name: Setup | User can sudo without password
    lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ remote_group }} ' line='%{{ remote_group }} ALL=(ALL) NOPASSWD: ALL'"


  handlers: 
    - name: dpkg-reconfigure
      command: dpkg-reconfigure locales
      environment: locale_env
      sudo: true
